
	<div class="col-md-12 " style="background:white;">
		<!-- <button data-target="#addWebServiceModal" data-toggle="modal" style="position:absolute;right:0;top:20px;" class="btn btn-info" style=""> <span class="glyphicon glyphicon-plus-sign"></span> Add WebMethod</button> -->

			<h3>Web Services Simulator <small>Beta</small></h3>
			<hr/>
			<h5>Welcome to Webservices Simulator. Now you can test your webservices very easily.</h5>
			<br/>
			<p>Navigate to the Controller &amp; Action you wish to test from Webservice panel. Then Click on Action link to test it.</p>
			<hr/>
			<section class='col-md-6 webserviceCont1 connectedSortable ui-sortable' style="min-height:300px;">
				<div class="formContainer col-md-12 box box-success" >
			    	<div class="box-header">
		                <h3 class="box-title">Create Web Service</h3>
		                <div class="box-tools pull-right">
		                    
		                    <!-- <button title="" data-toggle="tooltip" data-widget="remove" class="btn btn-default btn-sm" data-original-title="Remove"><i class="fa fa-times"></i></button> -->
		                </div>
		            </div>
		            <div class="box-body">
					<div class="form-group">
					    <label for="exampleInputEmail1">Name</label>
					    <input type="text" class="form-control" id="methodName" placeholder="Enter Method Name">
					</div>
					<div class="form-group">
					    <label for="exampleInputEmail1">Add params</label>
					    <div>
					    	<table class="table" id="paramCont">
					    		<tr >
					    			<td>
					    				 <input type="text" class="form-control col-md-10 params" name="params[]" placeholder="Param Name">
					    			</td>
					    			<td>
					    				 <input type="text" class="form-control col-md-10 params_default" name="params_default[]" placeholder="Default Value">
					    			</td>
					    			<td>
					    				  <button class="close">x</button>
					    			</td>
					    		</tr>
					    	</table>
						    
						  
					    </div>
					    <div class="clearfix"></div>
					    <hr/>
					</div>
					<div class="form-group">
						<button class="btn btn-primary" onclick="addParam();"><span class="glyphicon glyphicon-plus-sign"></span> Add param</button>
					</div>
					<button type="button" id="createWebMethod" class="btn btn-primary">Create</button>
					</div>
				</div>
			</section>
			<section class='col-md-6 webserviceCont2 connectedSortable ui-sortable' style="min-height:300px;">
				
			</section>
			
	</div>


<script type="text/javascript">
	$(function()
	{
		var pos=0;
		$(document).on("click",'.openWeb',function()
		{
			var data = $(this).attr('name');
			$.ajax({
				url:"<?php echo $this->appBase().'/admin/webservices/generateform'; ?>",
				data:{data:data},
				method:'POST',
				success:function(result)
				{
					if(++pos%2==0)
						$(".webserviceCont1").append(result);
					else
						$(".webserviceCont2").append(result);
				}
			});
		});
		$("#paramCont").on('click','.close',function(){
			$(this).parent().parent().remove();	
		});

		$("#createWebMethod").click(function(){
			var name = $("#methodName").val();
			var params =[];
			var params_default =[];
			$('.params').each(function(){

				params.push($(this).val());
			});
			$('.params_default').each(function(){

				params_default.push($(this).val());
			});
			var data ={};
			data['params']= params;
			data['params_default']= params_default;
			data['name']= name;
			//alert(JSON.Stringify(data));

			$.ajax({
				url:"<?php echo $this->appBase().'/admin/webservices/create'; ?>",
				
				data:{data:data},
				method:'POST',
				success:function(result)
				{
					alert(result)
				}
			});
		});

	});
	function addParam()
	{
		$("#paramCont").append('<tr><td><input type="text" class="form-control col-md-10 params" name="params[]" placeholder="Param Name"></td><td><input type="text" class="form-control col-md-10 params_default" name="params_default[]" placeholder="Default Value"></td><td><button class="close">x</button></td></tr>');
	}
	
</script>
<!-- 
<div class="modal fade" id="addWebServiceModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create New Web Service</h4>
      </div>
      <div class="modal-body">

	      	<div class="form-group">
			    <label for="exampleInputEmail1">Name</label>
			    <input type="text" class="form-control" id="methodName" placeholder="Enter Method Name">
			</div>
			<div class="form-group">
			    <label for="exampleInputEmail1">Add params</label>
			    <div>
			    	<table class="table" id="paramCont">
			    		<tr >
			    			<td>
			    				 <input type="text" class="form-control col-md-10 params" name="params[]" placeholder="Param Name">
			    			</td>
			    			<td>
			    				 <input type="text" class="form-control col-md-10 params_default" name="params_default[]" placeholder="Default Value">
			    			</td>
			    			<td>
			    				  <button class="close">x</button>
			    			</td>
			    		</tr>
			    	</table>
				    
				  
			    </div>
			    <div class="clearfix"></div>
			</div>
			<div class="form-group">
				<button class="btn btn-primary" onclick="addParam();"><span class="glyphicon glyphicon-plus-sign"></span> Add param</button>
			</div>
		  		
		     <p class="help-block">* We recommand to create a saperate layout for each Module. Add JS and CSS manually if not creating a saperate layout.</p> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="createWebMethod" class="btn btn-primary">Create</button>
      </div>
    </div>
  </div>
</div> -->
<script language="Javascript" type="text/javascript">
$(function(){
  $(".web_container span a").click(function(){
    $(this).parent().next().slideToggle();
  });
  $(".module_manager.modulecont").click(function(e)
  {
    if( e.target !== this ) 
       return;
    $('.module_manager .module').removeClass('active');
  });
  $(".module_manager.controllercont").click(function(e)
  {
    if( e.target !== this ) 
       return;
    $('.module_manager .controller').removeClass('active');
  });
});

</script>