
    <div class="content-section-a" style="background:#fff;margin-top:50px;">

        <div class="container">

            <div class="row">
               
                <div class="col-md-8 " style="margin-bottom:20px;" >
                   <h2>Contact Us</h2>
                   <hr/>
                   <p>

                    We are here to answer any query you may have about Fork PHP. Reach out to us and we'll respond as soon as we can.

                    Even if there is something you have always wanted to experience and can't find it on Fork PHP, let us know and we promise we'll do our best to develop it for you.
                    </p>
                    <?php 
                    @session_start();
                        if(isset($_SESSION['success']))
                        {
                            if($_SESSION['success']==true)
                            {
								unset($_SESSION['success']);
                                echo "<div class='alert alert-success'>Thank you. Your query has been submitted. We'll get back to you soon on your query</div>";
                            }
                            else
                            {
                                echo "<div class='alert alert-danger'>Sorry, an error occurred while submitting your query. Please try again in a while.</div>";
                            }
                           
                        }

                    ?>
                   <form role="form" method="POST" action="<?php echo $this->appBase().'/default/index/processContact'; ?>">
                      <div class="form-group">
                        <label for="name">Your Name</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name">
                      </div>
                      <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control required" id="email" name="email" placeholder="Email">
                      </div>
                      <div class="form-group">
                        <label for="subject">Subject</label>
                        <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject">
                      </div>
                      <div class="form-group">
                        <label for="message">Your Query</label>
                          <textarea aria-required="true" role="textbox" class="required form-control" id="message" name="message" rows="8"></textarea>
                        
                      </div>
                      <button type="submit" onclick="return validate();" class="btn btn-default">Submit</button>
                    </form>


                </div>
                <div class="col-md-3 col-md-offset-1" style="background:#efefef;padding:20px;border-radius:5px;">
                    <div class="form-group">
                        <label>Author</label>
                        <p> Tom Wased </p>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <p> admin@forkphp.com </p>
                    </div>
                    <div class="form-group">
                        <label>Telephone</label>
                        <p> +91-9958865390 </p>
                    </div>
                    
                </div>
                 <div class="fb-like-box fb_iframe_widget col-md-3 col-md-offset-1" data-href="https://www.facebook.com/forkMVC" data-height="300" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false" style="padding:0;margin-top:30px;"></div>
            </div>

        </div>
        <!-- /.container -->

    </div>

     <script type="text/javascript">
    function validate() {
        var email = $('#email').val().trim();
        var name = $('#name').val().trim(); 
        var message = $('#message').val().trim();
        var alertMessage="";
        if(!email)
        {
           //bootbox.alert("Please enter an email address.");
           alertMessage +="Please Enter an Email Address.<br/>";
           
        }
        if(!message)
        {
           alertMessage +="Please Write Your Message before sending email.<br/>"; 
        }
        if(!name)
        {
           alertMessage +="Please Write Your Name.<br/>"; 
        }
        if(alertMessage.length >0)
        {
            bootbox.alert(alertMessage);
            return false;
        }
        else
        {
            return true;
        }
    }
    </script>
    <div id="fb-root"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=301707516704438&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>