
    <div class="content-section-a" style="background:#fff;margin-top:50px;">

        <div class="container">

            <div class="row">
               
                <div class="col-md-8 " style="margin-bottom:20px;" >
                   <h2>Download </h2>
                   <hr/>
                   <p>

                    The latest Fork PHP version is 1.2, Download it Now from Codeplex / Github.
                    </p>
                    <br/>
                    <a style="display:inline-block;padding:7px 32px;" class="btn btn-default" href="https://github.com/ForkPHP/latest">GitHub</a>
                    <a class="btn btn-default" style="display:inline-block;padding:7px 32px;" href="https://forkphp.codeplex.com/SourceControl/latest">Codeplex</a>

                    <h2>Licence</h2>
                    <hr/>
                    <p>
                       You may use any Fork PHP under the terms of MIT License .

                        The MIT License is recommended for most projects. It is simple and easy to understand and it places almost no restrictions on what you can do with Fork PHP library.

                    </p>
                    <br/>
                    <h3>MIT Licence</h3>
<textarea readonly="readonly" class="form-control" style="min-height:240px;box-shadow:none;cursor:initial;resize:vertical">
The MIT License (MIT)

Copyright (c) 2014 Tom Wased

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

</textarea>
    <br/>
              <p> Fork PHP is licenced under MIT, you're free to modify and contribute to its library. So download and Start development today.  </p>
                    
                   


                </div>
                <div class="col-md-3 col-md-offset-1" style="background:#efefef;padding:20px;border-radius:5px;">
                    <div class="form-group">
                        <label>Author</label>
                        <p> Tom Wased </p>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <p> admin@forkphp.com </p>
                    </div>
                    <div class="form-group">
                        <label>Telephone</label>
                        <p> +91-9958865390 </p>
                    </div>
                    
                </div>
                 <div class="fb-like-box fb_iframe_widget col-md-3 col-md-offset-1" data-href="https://www.facebook.com/forkMVC" data-height="300" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false" style="padding:0;margin-top:30px;"></div>
            </div>

        </div>
        <!-- /.container -->

    </div>


    <div id="fb-root"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=301707516704438&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>