
  <!-- PAGE CONTENT --> 
  <div class="container">
    <div class="col-lg-8 col-lg-offset-2 text-center" style="color:white;">
     <div class="logo">
       <h1><?php if($GLOBALS['ERROR_TYPE']==1){echo "Page not found!!";}else{echo "Something went wrong.";}?></h1>
     </div>
     <div class="clearfix"></div>            
     <div class="col-lg-8  col-lg-offset-2">
       <div class="input-group">
        <input type="text" placeholder="Write Your Message" class="form-control" />
        <span class="input-group-btn">
         <button class="btn btn-danger" type="button">Contact Support</button>
       </span>
     </div>
   </div>
   <div class="clearfix"></div>
   <br /><br />
   <p class="text-muted">Theere is some error here, Please try later. </p>
   <div class="clearfix"></div>
   <br /><br />
   <div class="col-lg-6 col-lg-offset-3">
    <form action="#">
      
      <div class="input-group">
        <input type="text" placeholder="search ..." class="form-control" />
        <span class="input-group-btn">
         <button class="btn btn-primary" type="button"><i class=" glyphicon glyphicon-search "></i></button>
       </span>
     </div>
     
   </form>
 </div>
 <div class="clearfix"></div>
 <br />
 <div class="col-lg-6  col-lg-offset-3">
  <div class="btn-group btn-group-justified">
    
    <a href="<?php echo $this->appBase();?>" class="btn btn-success">Return Website</a> 
  </div>
  
</div>

</div>


</div>