<div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Fork PHP	</h1>
                        <h3>A MVC Framework for Developers</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li><a href="https://twitter.com/forkPHP" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li><a href="https://www.facebook.com/pages/Fork-PHP/730383596982850" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                            </li>
                            <li><a href="https://plus.google.com/+ForkphpFramework" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">PLUS</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Light Weighted &amp; Strong Library.
                        <br></h2>
                    <p class="lead">Fork PHP comes along with its strong library.It enables you to use features like PHP Controls , <strong> Entity Framework</strong> Methods and MVC structure. </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="<?php echo $this->baseUrl().'/img/ipad.png'; ?>" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading"> Easy to Learn and Implement
                        <br></h2>
                    <p class="lead">Fork PHP is very easy to learn and use. You will need to look for <strong>documentation</strong> once, and It will enable you to start development.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="<?php echo $this->baseUrl().'/img/doge.png'; ?>" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">
                    Open Source 
                        </h2>
                    <p class="lead">
                        Fork PHP is inspired with available Frameworks like Zend PHP &amp; ASP MVC 4.0. But Fork PHP falls in Open Source Category. You are free to modify its library according to your requirments with a free Licence.
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="<?php echo $this->baseUrl().'/img/phones.png'; ?>" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

    <script src="http://localhost:3556/script.js/dd" />
