<div class="col-md-4 col-md-offset-4 signup login col-sm-offset-3 col-sm-6 col-xs-9 col-xs-offset-1" >

    <h3> <img src="<?php echo $this->baseUrl().'/img/user.png'; ?>"> Create New Account</h3>
    <br/>
    <form method="post" role="form"  action="<?php echo $this->appBase().'/default/accounts/processSignup';?>">
      <div class="form-group">
        <input type="text" class="form-control" name="name" id="name" placeholder="Name">
      </div>
      <div class="form-group">
        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
      </div>
      <div class="form-group">  
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
      </div>
      <div class="form-group">  
        <input type="password" class="form-control" id="repassword" name="repassword" placeholder="Confirm Password">
      </div>
       <?php
        if(isset($this->view['msg']))
        {
          echo "<div class='alert alert-danger'>".base64_decode($this->view['msg'])." </div>";
        }

       ?>
      <div class="form-group">  
        <input type="submit" class="btn btn-primary" value="Create Account">
      </div>
    </form>

</div>
