
<div class="login_m col-md-12" >
<?php 
$msg = $this->get('msg');
if(!empty($msg))
{
	$msg = base64_decode($this->get('msg'));
	echo "<div class='alert alert-success'> $msg </div>";
}

?>
	<div class="col-md-4"></div>
	<div class="login col-md-4 ">
	<h3> <img src="<?php echo $this->baseUrl().'/img/user.png'; ?>"> Fork PHP : Front End Login</h3>
	<form role="form" method="post" action="<?php echo $this->appBase().'/default/accounts/processlogin'; ?>">
	  <div class="form-group">
	    <label for="username">Email address</label>
	    <input type="email" class="form-control" id="username" name="username" placeholder="Enter email"> 
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	  
	</form>
	<?php 
	if(isset($this->view['has_error']) && $this->view['has_error']==1)
	{
		echo "<br/><div class='alert alert-danger'>
	  			login failed !!!
			    </div>";
	}

	?>
	</div>
	<div class="col-md-4"></div>
</div>
