<?php
$this->appendJS("jquery.min.js");
$this->appendJS("bootstrap.min.js");
$this->appendCSS("bootstrap.min.css");
$this->appendCSS("AdminLTE.css",$this->baseUrl()."/AdminLTE/css");
$this->appendCSS("admin/style.css");


?>


<div class="form-box" id="login-box">
    <div class="header">Sign In : <?php echo APP_NAME; ?></div>
    <form role="form" method="post" action="<?php echo $this->appBase().'/admin/login/processlogin'; ?>">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" id="username" name="username" class="form-control" placeholder="Email"/>
            </div>
            <div class="form-group">
                <input type="password" id="password" name="password" class="form-control" placeholder="Password"/>
            </div>          
            <div class="form-group">
                <input type="checkbox" name="remember_me"/> Remember me
            </div>
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Sign me in</button>  
            
            <p><a href="#">I forgot my password</a></p>
            
            
        </div>
    </form>
    <?php 
	if(isset($this->view['has_error']) && $this->view['has_error']==1)
	{
		echo "<br/><div class='alert alert-danger'>
	  			login failed !!!
			    </div>";
	}

	?>
</div>
<script type="text/javascript">
	 $('html,body').addClass('bg-black');
</script>