<?php
$this->appendJS("jquery.min.js");
$this->appendJS("bootstrap.min.js");
$this->appendCSS("bootstrap.min.css");
$this->appendCSS("AdminLTE.css",$this->baseUrl()."/AdminLTE/css");
$this->appendCSS("admin/style.css");


?>
<!-- <div class="">
	<div class="col-md-4"></div>
	<div class="login col-md-4 ">
	<h3> <img src="<?php echo $this->baseUrl().'/img/user.png'; ?>"> Fork PHP : Admin Login</h3>
	<form role="form" method="post" action="<?php echo $this->appBase().'/admin/login/processlogin'; ?>">
	  <div class="form-group">
	    <label for="username">Email address</label>
	    <input type="email" class="form-control" id="username" name="username" placeholder="Enter email"> 
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	  
	</form>
	<?php 
	if(isset($this->view['has_error']) && $this->view['has_error']==1)
	{
		echo "<br/><div class='alert alert-danger'>
	  			login failed !!!
			    </div>";
	}

	?>
	</div>
	<div class="col-md-4"></div>
</div>
 -->

<div class="form-box" id="login-box">
    <div class="header">Sign In : <?php echo APP_NAME; ?></div>
    <form role="form" method="post" action="<?php echo $this->appBase().'/admin/login/processlogin'; ?>">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" id="username" name="username" class="form-control" placeholder="Email"/>
            </div>
            <div class="form-group">
                <input type="password" id="password" name="password" class="form-control" placeholder="Password"/>
            </div>          
            <div class="form-group">
                <input type="checkbox" name="remember_me"/> Remember me
            </div>
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Sign me in</button>  
            
            <p><a href="#">I forgot my password</a></p>
            
            
        </div>
    </form>
    <?php 
	if(isset($this->view['has_error']) && $this->view['has_error']==1)
	{
		echo "<br/><div class='alert alert-danger'>
	  			login failed !!!
			    </div>";
	}

	?>
</div>
<script type="text/javascript">
	 $('html,body').addClass('bg-black');
</script>