<?php
$this->appendJS("jquery.min.js");
$this->appendJS("bootstrap.min.js");
$this->appendCSS("bootstrap.min.css");
$this->appendCSS("bootstrap-theme.min.css");
$this->appendCSS("admin/style.css");


?>
<div class="">
	<div class="col-md-4"></div>
	<div class="login col-md-4 ">
	<h3> <img src="<?php echo $this->baseUrl().'/img/user.png'; ?>"> Fork PHP : Admin Login</h3>
	<form role="form" method="post" action="<?php echo $this->appBase().'/admin/login/processlogin'; ?>">
	  <div class="form-group">
	    <label for="username">Email address</label>
	    <input type="email" class="form-control" id="username" name="username" placeholder="Enter email"> 
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	  
	</form>
	<?php 
	if(isset($this->view['has_error']) && $this->view['has_error']==1)
	{
		echo "<br/><div class='alert alert-danger'>
	  			login failed !!!
			    </div>";
	}

	?>
	</div>
	<div class="col-md-4"></div>
</div>
