<?php

//print_r($this->view['dblist']);
$this->appendJS("../src-noconflict/ace.js");

?>
<div class="col-md-12  col-sm-12 ">
	<form class="navbar-form navbar-right" role="search">
	<a href="<?php echo $this->appBase().'/admin/entity/logout'; ?>" class="btn btn-info">Logout (Logged in as <?php echo $_SESSION['mysql_username']; ?>)</a>
	</form>
	<br style="clear:both;">
	<div class="col-md-7 col-sm-10 col-xs-10 cont">
		<h3>Entity Generator</h3>
		<br/>
		<div class="form-group ">
		    <label for="dbname">Chose Database</label>
		    <div class="col-md-10 col-sm-10 col-xs-10" style="padding-left:0px;">
		    <select class="form-control" id="dbname" name="db">
		    <?php 
		    	foreach ($this->view['dblist'] as $value) {
		    	echo "<option value=$value>".$value."</option>";
		    	}
		    ?>
			</select>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-2">
				<input type="button" class="btn btn-primary" style="float:left;" value="Submit" id="loadTables">
			</div>
			
		</div>
		<div class="form-group" id="tablelist" style="padding-left:0px;height=200px;padding-top:25px;">
			

		</div>
	</div>
</div>
<script>
   
</script>

