
<div class="login col-md-6 col-md-offset-3">
	<h3> <img src="<?php echo $this->baseUrl().'/img/user.png'; ?>"> Fork PHP : Mysql Login</h3>
	<form role="form" method="post" action="<?php echo $this->appBase().'/admin/entity/mysqllogin'; ?>">
	  <div class="form-group">
	    <label for="username"> Username</label>
	    <input type="text" class="form-control" id="username" name="username" placeholder="Username"> 
	  </div>
	  <div class="form-group">
	    <label for="password">Password</label>
	    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	  
	</form>
	<?php 
	if(isset($this->view['has_error']) && $this->view['has_error']==1)
	{
		echo "<br/><div class='alert alert-danger'>
	  			login failed !!!
			    </div>";
	}

	?>
	</div>