<?php

$this->appendCSS("../codemirror/lib/codemirror.css");
$this->appendCSS("../codemirror/theme/monokai.css");
$this->appendCSS("../codemirror/addon/display/fullscreen.css");
$this->appendCSS("jquery-ui-1.10.4.custom.min.css");
$this->appendJS("../codemirror/lib/codemirror.js");
$this->appendJS("../codemirror/mode/properties/properties.js");
?>


<style type="text/css" media="screen">
    
    
    .editor 
    { 
      height:200px;   
    }
  </style>

<div class="container" style="width:100%;padding:0;">
	<div class="col-md-12  col-sm-12 ">
		<h3>Fork PHP : Settings</h3>
		<hr/>
		
	</div>
</div>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Application Settings
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <?php 

      foreach ($this->view['inifiles'] as $key => $value) 
      {
        echo "<h3>".$key."</h3><br/>";
        $name = str_replace(".ini", "", $key);
        echo"<textarea class='editor form-control ' id=$name>$value</textarea>";
        echo "<input type='button'  class='btn btn-primary inifile' rel=$name value='Save' />";
        echo "<br/>";
      }
     
      
 

    ?>
      </div>
    </div>
  </div>
 
</div>
<script type="text/javascript">
$(document).ready(function(){
$('.inifile').click(function()
  {
    var file = $(this).attr("rel");
    
    var content = editors[file].getValue();
    
    $.ajax({
         type: "POST",
         data: {file:file+".ini",content:content},
         url: "<?php echo $this->appBase().'/admin/settings/updateInI'; ?>",
         success: function(msg)
         {
            bootbox.alert(msg,function(){});
         }
      });

  });

  var editors={};
  $('.editor').each(function(index,object)
  {
    var name = $(object).attr('id');
     editors[name] =  CodeMirror.fromTextArea(object, {
        lineNumbers: true,
          theme: "default",
            mode:  'text/x-ini',
            extraKeys: {
                  "F11": function(cm) {
                    cm.setOption("fullScreen", !cm.getOption("fullScreen"));
                    $(".navbar-fixed-top").toggle();
                  },
                  "Esc": function(cm) {
                    if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
                    $(".navbar-fixed-top").toggle();
                  }
                }
      });
     /* editors['"'+name+'"'].setValue(content)
      editors['"'+name+'"'].setSize('100%','510');*/
  });

});
  
</script>