<?php
$this->appendJS("../src-noconflict/ace.js");

?>


<style type="text/css" media="screen">
    
    
    .editor 
    { 
      height:200px;   
    }
  </style>

<div class="container" style="width:100%;padding:0;">
	<div class="col-md-12  col-sm-12 ">
		<h3>Fork PHP : Settings</h3>
		<hr/>
		
	</div>
</div>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Application Settings
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <?php 

      foreach ($this->view['inifiles'] as $key => $value) 
      {
        echo "<h3>".$key."</h3><br/>";
        $name = str_replace(".ini", "", $key);
        echo"<pre class='editor' id=$name>$value</pre>";
        echo "<input type='button'  class='btn btn-primary inifile' rel=$name value='Save' />";
        echo "<br/>";
      }
      foreach ($this->view['inifiles'] as $key => $value) 
      {
        $name = str_replace(".ini", "", $key);
        echo "<script>";
        echo"var $name = ace.edit('".$name."');
            $name.setTheme('ace/theme/twilight');
            $name.getSession().setMode('ace/mode/ini');";
        echo "</script>";
      }
      
 

    ?>
      </div>
    </div>
  </div>
  <!--
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Front End User Settings
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Collapsible Group Item #3
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div> -->
</div>
<script type="text/javascript">
  $('.inifile').click(function()
  {
    var file = $(this).attr("rel");
    file = eval(file);
    var content = file.getValue();
    $.ajax({
         type: "POST",
         data: {file:file,content:content},
         url: "<?php echo $this->appBase().'/admin/settings/updateInI'; ?>",
         success: function(msg)
         {
            bootbox.alert(msg,function(){});
         }
      });

  });
</script>