
<?php
// +----------------------------------------------------------------------+
// | Fork PHP :: Layout                                                   |
// +----------------------------------------------------------------------+
// | Copyright (c) 2013-2014 Fork PHP Team                                |
// +----------------------------------------------------------------------+
// | This source file is a Template for the Default Layout. It falls      |
// | under MIT Licence. Code is generated via Module Manager.             |
// +----------------------------------------------------------------------+
// | Authors: Eshant Sahu <eshantsahu@forkphp.com>                        |
// +----------------------------------------------------------------------+
//

/**
* If you do not want to include this block in your code, You can modify it in the lib->template->layout
* @author   Eshant Sahu <eshantsahu@forkphp.com>
* @version  1.0.1.2
* @access   public
*/

$this->appendJS("jquery.min.js");
$this->appendJS("bootstrap.min.js");
$this->appendJS("jquery.cookie.js");
$this->appendJS("jquery.treeview.js");
$this->appendJS("bootbox-4.1.0.min.js");
$this->appendJS("admin/admin.js");
$this->appendCSS("bootstrap.min.css");
$this->appendCSS("jquery.treeview.css");
$this->appendCSS("admin/style.css");
$this->meta(array('name' =>'es' ,'val'=>'ess' ));
$obj = new adminlayoutController();
$user = $obj->test();
echo "<script>var APP_BASE = '".$this->appBase()."' </script>";
$iconPath= $this->baseUrl().'/img/icon.png';
  $this->headString("<link rel='icon' href=$iconPath type='image/x-icon'>");
?>

<script language="Javascript" type="text/javascript">
    $(document).ready(function()
    {
        $("#browser a").click(function()
        {
          var name = $(this).text().replace('.','_');
          var path = $(this).attr('file');
          var ext = $(this).attr('ext');
          addTab(name,ext,path);
        });
         
    });
  
  
  </script>
<nav role="navigation" class="navbar navbar-default navbar-fixed-top" style="margin-bottom:0px;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button data-target=".navbar-ex1-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="<?php echo $this->appBase().'/admin/home'; ?>" class="navbar-brand"><?php echo APP_NAME; ?> Admin</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">

    <ul class="nav navbar-nav navbar-left navbar-user">
      <li class=""><a href="<?php echo $this->appBase().'/admin/home/editor';?>"><span class="glyphicon glyphicon-edit"></span> Code Editor</a></li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Tools <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->appBase().'/admin/entity';?>">Entity Class Generator</a></li>
            <li><a href="<?php echo $this->appBase().'/admin/entity/dbmanager';?>">DB Manager</a></li>
            <?php
              // add plugins 
              $config = new appConfig("application",$host);
              $iniData = $config->get();
              $plugins = $iniData["plugins"];
              $modules=explode(",", $plugins['names']);
              foreach ($modules as $value) 
              {
                if($plugins[$value.".enable"]=="1")
                {
                  echo "<li><a href=".$this->appBase()."/".$plugins[$value.".url"].">".$plugins[$value.".text"]."</a></li>";
                }
              }

            ?>
           <!--  <li><a href="#">Something else here</a></li>
           <li class="divider"></li>
           <li><a href="#">Separated link</a></li> -->
            <li class="divider"></li>
            <li><a href="http://www.forkphp.com/document" target="_blank">Browse Documentation</a></li>
          </ul>
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right navbar-user">

    

      <li class="dropdown user-dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="fa fa-user"></i> <label id='userName'>User Name</label> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<?php echo $this->appBase().'/admin/profile'; ?>"><i class="fa fa-user"></i> Profile</a></li>
         <!--  <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li> -->
          <li><a href="<?php echo $this->appBase().'/admin/settings'; ?>"><i class="fa fa-gear"></i> Settings</a></li>
          <li class="divider"></li>
          <li><a href="<?php echo $this->appBase().'/admin/home/logout'; ?>"><i class="fa fa-power-off"></i> Log Out</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<div class="row" style="padding:0;width:100%; margin-top: -20px;">
  
      <div class="col-md-2 col-sm-3 col-xs-12 file_list" style="padding-right:0;">
      
        <?php 
          $libObj = new Fork_Lib();
          if($libObj->getControllerName()=="home" && $libObj->getActionName()=="editor")
          {$this->partial("filemanager"); }
          if($libObj->getControllerName()=="webservices") // show webservices tree
          {
            echo "<div style='background:#414141;color:#fff;font-weight:bold;text-align:center;height:40px;line-height:40px;margin-bottom:10px;'><span class='home'></span>Web Services</div>";
            $webservice = new webservice();
            $classes = $webservice->getClasses();
            $classes=array_diff($classes, array("admin_webservicesController"));
            foreach ($classes as  $class)
            {
              echo "<div class='web_container'><span><a>".str_replace("webservice_", "", $class)."</a></span>";
              echo "<ul class='service'>";
              $methods =array_diff(get_class_methods($class), get_class_methods('Controller'));
              foreach ($methods as $method)
              {
                $echoStr= "";
                $echoStr.= "<ul>";
                $r = new ReflectionMethod($class, $method);
                $params = $r->getParameters();
                $thisParams = "This Method requires : ".implode(", ", $params);
                foreach ($params as $param) {
                    //$param is an instance of ReflectionParameter
                    $echoStr.= "<li><a title='".$param."'>".$param->getName()."</a></li>";
                    //echo $param->isOptional()."<br/>";

                }
                echo "<li><a name='".$class."#".$method."' title='".$thisParams."' class='openWeb'>".$method."( )</a></li>".$echoStr;
                echo "</ul>";
              }
              echo "</ul></div>";
            }
          }

        ?>
      </div>
      <div class="col-md-10 col-md-offset-2 col-sm-9 col-sm-offset-3 col-xs-12 ">
        <?php $this->view(); ?>
      </div>
  
</div>
<script type="text/javascript">
 $.ajax({
       type: "POST",
       url: "<?php echo $this->appBase().'/admin/profile/getProfile'; ?>",
       success: function(jdata)
       {
        var data = $.parseJSON(jdata);
        $("#userName").text(data['name']);
        
       }
    }); 
 $('.folder').bind("contextmenu", function(event) {
    event.preventDefault();
    var folder = $(this).attr('folder');
    var html = "<div class='custom-menu'><ul><li class='new_file'>New File</li><li class='new_folder'>New Folder</li><li class='delete_folder'>Delete Folder</li></ul></div>";
    var html = "<ul class='dropdown-menu custom-menu'><li id='new_file' onclick=addfile('"+folder+"')><a href='#'><i class='glyphicon glyphicon-plus'></i> New File</a></li><li id='new_folder' onclick=addfolder('"+folder+"')><a href='#'><i class='glyphicon glyphicon-plus'></i> New Folder</a></li><li onclick=renamefolder('"+folder+"')><a href='#'><i class='glyphicon glyphicon-pencil'></i> Rename Folder</a></li><li onclick=delfolder('"+folder+"')><a href='#'><i class='glyphicon glyphicon-trash'></i> Delete Folder</a></li></ul>";
    $(html)
        .appendTo("body")
        .css({top: event.pageY + "px", left: event.pageX + "px"});
});
 $(document).bind("click", function(event) {
    $("ul.custom-menu").remove();

});
if($.cookie('tabs'))
{
  if($("#editorTab").length>0)
  {
    var tabsValue = $.cookie("tabs").split(",");
    var i=1;
  $.each( tabsValue, function(index,value)
  {
    if(value.length>0)
    {
        
      var tabContent = value.split("#");
      addTab(tabContent[0],tabContent[1],tabContent[2],index+1);
      if(i==tabsValue.length)
      {
        getfiles();
      }
      i++;
    }
  });
  }
  
}
$(function(){
  $(".web_container span a").click(function(){
    $(this).parent().next().slideToggle();
  });
  $(".module_manager.modulecont").click(function(e)
  {
    if( e.target !== this ) 
       return;
    $('.module_manager .module').removeClass('active');
  });
  $(".module_manager.controllercont").click(function(e)
  {
    if( e.target !== this ) 
       return;
    $('.module_manager .controller').removeClass('active');
  });
})

</script>