<header role="banner" id="top" class="navbar navbar-static-top bs-docs-nav" style="background:white;">
  <div class="container">
    <div class="navbar-header">
      <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" title="<?php echo APP_NAME;?>" href="<?php echo $this->appBase().'/default'; ?>"><?php echo APP_NAME;?></a>
    </div>
    <nav role="navigation" class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <?php 
      if(isset($_SESSION['userid']))
      {
      ?>
        <li >
         <a id="userName">  </a>
        </li>
        
        <li class="dropdown user-dropdown">
          <a href="<?php echo $this->appBase().'/default/home/logout'; ?>"><i class="fa fa-power-off"></i> Log Out</a>
        </li>

      <?php 

        }
        else
        {
          ?>
            <li><a  href="<?php echo $this->appBase().'/default/accounts/login'; ?>">Login</a></li>
        <li><a  href="<?php echo $this->appBase().'/default/accounts/create'; ?>">SignUp</a></li>

        <?php
        }

      ?>
      </ul>
    </nav>
  </div>
</header>
<?php 
if(isset($_SESSION['userid']))
{
?>
<script>
 $.ajax({
       type: "POST",
       url: "<?php echo $this->appBase().'/default/home/getProfile'; ?>",
       success: function(jdata)
       {
        var data = $.parseJSON(jdata);
        if(data['name'])
        $("#userName").html("Welcome, <b>"+data['name']+"</b>");
        else
          $("#userName").html("Welcome, <b>"+data['username']+"</b>");
        
       }
    }); 
</script>

<?php
}
?>