<?php
// +----------------------------------------------------------------------+
// | Fork PHP :: Layout                                                   |
// +----------------------------------------------------------------------+
// | Copyright (c) 2013-2014 Fork PHP Team                                |
// +----------------------------------------------------------------------+
// | This source file is a Template for the Default Layout. It falls      |
// | under MIT Licence. Code is generated via Module Manager.             |
// +----------------------------------------------------------------------+
// | Authors: Eshant Sahu <eshantsahu@forkphp.com>                        |
// +----------------------------------------------------------------------+
//

/**
* If you do not want to include this block in your code, You can modify it in the lib->template->layout
* @author   Eshant Sahu <eshantsahu@forkphp.com>
* @version  1.0.1.2
* @access   public
*/

$this->appendJS("jquery.min.js");
$this->appendJS("bootstrap.js");
$this->appendJS("jquery.cookie.js");
$this->appendJS("jquery.treeview.js");
$this->appendJS("prism.js");
$this->appendJS("bootbox-4.1.0.min.js");
$this->appendJS("default/default.js");
$this->appendCSS("bootstrap.css");
$this->appendCSS("jquery.treeview.css");
$this->appendCSS("prism.css");
$this->appendCSS("font-awesome/css/font-awesome.min.css");
$this->appendCSS("landing-page.css");
$this->meta(array('name'=>'viewport','content'=>'width=device-width, initial-scale=1.0'));
$this->meta("charset","utf-8");
$this->meta(array('name'=>'description','content'=>'Fork PHP : A MVC Framework'));
$this->title('Fork PHP : Official Website');
$iconPath= $this->baseUrl().'/img/icon.png';
$this->headString("<link rel='icon' href=$iconPath type='image/x-icon'>");

?>


    <!-- Custom Google Web Font -->
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

    <!-- Add custom CSS here -->


    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom:0px;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Fork PHP</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->appBase();?>">Fork PHP</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->appBase().'/home';?>">Home</a>
                    </li>
                    <li><a href="<?php echo $this->appBase().'/document';?>">Documentation</a>
                    </li>
                    <li><a href="<?php echo $this->appBase().'/tutorials';?>">Tutorials</a>
                    </li>
                    <li><a href="<?php echo $this->appBase().'/download';?>">Download</a>
                    </li>
                    <li><a href="<?php echo $this->appBase().'/contact';?>">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    
    <!-- /.content-section-a -->
    <?php echo $this->view(); ?>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h3>Download and Start Development Now </h3>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li><a href="https://twitter.com/forkPHP" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li><a href="https://www.facebook.com/pages/Fork-PHP/730383596982850" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li><a href="https://plus.google.com/+ForkphpFramework" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">PLUS</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="<?php echo $this->appBase().'/home';?>">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="<?php echo $this->appBase().'/document';?>">Documentation</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="<?php echo $this->appBase().'/tutorials';?>">Tutorials</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="<?php echo $this->appBase().'/contact';?>">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Fork PHP 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57126298-1', 'auto');
  ga('send', 'pageview');

</script>