<?php
// +----------------------------------------------------------------------+
// | Fork PHP :: Layout                                                   |
// +----------------------------------------------------------------------+
// | Copyright (c) 2013-2014 Fork PHP Team                                |
// +----------------------------------------------------------------------+
// | This source file is a Template for the Default Layout. It falls      |
// | under MIT Licence. Code is generated via Module Manager.             |
// +----------------------------------------------------------------------+
// | Authors: Eshant Sahu <eshantsahu@forkphp.com>                        |
// +----------------------------------------------------------------------+
//

/**
* If you do not want to include this block in your code, You can modify it in the lib->template->layout
* @author   Eshant Sahu <eshantsahu@forkphp.com>
* @version  1.0.1.2
* @access   public
*/

  $this->appendJS("jquery.min.js");
  $this->appendJS("bootstrap.min.js");
  $this->appendJS("bootbox-4.1.0.min.js");
  $this->appendJS("forklib.js");
  $this->appendCSS("bootstrap.min.css");
  $this->appendCSS("bootstrap-theme.min.css");
  $this->appendCSS("default/style.css");
  $iconPath= $this->baseUrl().'/img/icon.png';
  $this->headString("<link rel='icon' href=$iconPath type='image/x-icon'>"); // set icon
  $this->partialLayout("defaultheader");
?>

<?php $this->view(); ?> 