
<script type="text/javascript">
</script>

<?php
$files = $this->view['files'];

?>

<?php 
$this->appendCSS("../codemirror/lib/codemirror.css");
$this->appendCSS("../codemirror/theme/monokai.css");
$this->appendCSS("../codemirror/addon/display/fullscreen.css");
//$this->appendCSS("jquery-ui-1.10.4.custom.min.css");
$this->appendJS("../codemirror/lib/codemirror.js");
$this->appendJS("../codemirror/mode/javascript/javascript.js");
$this->appendJS("../codemirror/mode/htmlmixed/htmlmixed.js");
$this->appendJS("../codemirror/mode/php/php.js");
$this->appendJS("../codemirror/mode/css/css.js");
$this->appendJS("../codemirror/mode/xml/xml.js");
$this->appendJS("../codemirror/mode/clike/clike.js");
$this->appendJS("../codemirror/mode/turtle/turtle.js");
$this->appendJS("../codemirror/mode/properties/properties.js");
$this->appendJS("../codemirror/addon/display/fullscreen.js");
//$this->appendJS("jquery-ui-1.10.4.custom.min.js");
if(isset($this->view['files']))
{

	@$cookTabs = explode(",", ltrim($_COOKIE['tabs'],','));
	
	$files = $this->view['files'];

	foreach ($files as $file)
	{
		if(!in_array($file['name']."#".$file['ext']."#".$file['path'],$cookTabs))
			$cookTabs[]=$file['name']."#".$file['ext']."#".$file['path'];
	}

	$cookTabs = implode(',', $cookTabs);

	setcookie('tabs',$cookTabs);
}
?>


  <div class="" style="margin-top:15px;">
 	<ul class="nav nav-tabs editorTab" id="editorTab">
	  
	</ul>

	<!-- Tab panes -->
	<div class="tab-content" id="editorBody">
	 
	</div>
</div>
	<script>
	$(function(){
		getfiles();
		if(!areCookiesEnabled()){
			bootbox.alert("Please enable cookies so that Editor can manage its state over multiple tabs.");
		}
	});
	function areCookiesEnabled()
	{
		var cookieEnabled = (navigator.cookieEnabled) ? true : false;

		if (typeof navigator.cookieEnabled == "undefined" && !cookieEnabled)
		{ 
			document.cookie="testcookie";
			cookieEnabled = (document.cookie.indexOf("testcookie") != -1) ? true : false;
		}
		return (cookieEnabled);
	}
	</script>