<!-- <fieldset>
		<textarea id="sourceeditor" style="height: 250px; width: 100%;" name="test_2">
		</textarea>
		<p>Custom controls:<br />
			<input type='button' onclick='open_file1()' value='open file 1' />
			<input type='button' onclick='open_file2()' value='open file 2' />
			<input type='button' onclick='close_file1()' value='close file 1' />
			<input type='button' onclick='add()' value='Add' />
		</p>
</fieldset>
 -->

 <div class="container">
 	<h3> Editor Update Awaited</h3>
 	<hr/>
 	<p> Editor will be available with next update.</p>
 </div>