
 <div class="container">
 	<h3> Fork PHP Admin : Home</h3>
 	<hr/>
 	<h4> Welcome, Thanks for trying Fork PHP .</h4>
 	<br/>
 	<p> Please go through our Documentation for starting Development using Fork PHP.</p>
 	<br/>
 	<p> Regarding your query you can contact us at our official email <a href="mailto:info@forkphp.com">info@forkphp.com</a> </p>
 	<br/>
 	<p>Some of the features are still awaiting the updates, We will publish the updates as soon as it will be possible.</p>
 </div>