 <div class="center" id="locker" style="display:none;">            
                <div class="headline text-center" id="time">
                
                </div>
                <h2 style="color:white;" align="center">Click to Unlock</h2>
        </div>

        <!-- jQuery 2.0.2 -->
        
        <!-- Bootstrap -->
        

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });
    $(function(){
            checkInactivity();
    })
        
            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }
            function checkInactivity(){
                var time =0;
                var inactivityTimer = setInterval(function () {
                     time++;
                  //   console.log(time);
                     if(100==time){
                        startTime();
                        $(".center").center();
                        $(window).resize(function() {
                            $(".center").center();
                        });
                        $('#locker').css('display','block');
                        $('html').addClass('lockscreen');
                        $('.wrapper').remove();
                        clearInterval(inactivityTimer);
                        
                     }

                }, 1000);
                //$('*').bind('mousemove click mouseup mousedown keydown keypress keyup submit change mouseenter scroll resize dblclick', 
                     $('*').bind('click keydown keypress dblclick', function () {
                            if(time<100){
                                time=0;
                            }
                            else{
                            location.reload();    
                            //alert('reload')
                            }
                             $('.dropdown-menu.custom-menu').remove();
                        });
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>